### ISSUE TITLE
How to properly generate ZigBee Production Configuration using mfg_tool (TZ-426)

### ISSUE THREAD

**Issue by valdisz** [espressif/esp-zigbee-sdk#155]
### Question

The configuration record I was creating with the `mfg_tool` was not correct and caused troubles so that I could not join the ZigBee network (see this issue for more details #154).

Where can I read about the requirements and usage of the parameters that I need to pass to the `mfg_tool` so that later it works correctly with the ZigBee protocol?

**Comment by xieqinan** [comment]
@valdisz ,

First, please refer to the `mfg_tool` [README.md](https://github.com/espressif/esp-zigbee-sdk/blob/main/tools/mfg_tool/README.md) to learn how to generate and flash the manufacturer information. Note that it is better to use the command `python esp_zb_mfg_tool.py -i 966b9f3ef98ae6059708 -m CAFEBEEF50C0FFED -c 0x07FFF800 -mn Espressif -mc 0x131B` instead of `python esp_zb_mfg_tool.py -i 966b9f3ef98ae6059708 -m CAFEBEEF50C0FFED -c 0x8000 -mn Espressif -mc 0x131B`.

Second, if the end device with the manufacturer information is expected to join the network, The coordinator need to set `INSTALLCODE_POLICY_ENABLE` to true and use the `esp_zb_secur_ic_add()` function to add the manufacturer code of the end device.

Third, please compile and flash them.

**Comment by valdisz** [comment]
That README was the information source I used to generate Prod Conf sector all previous times. Setting `0x07FFF800` instead of `0x8000` does not make any difference, if Prod Conf is present, the end device cannot join.

I'm not programming a coordinator device. I'm building the end device, and the coordinator will be 3rd party device. I was using another esp32c6 as the coordinator only for testing purposes.

So here are the exact steps, commands I do, and outcome.

## Scenario 1
1. `idf.py -p COM15 erase-flash`
2. `idf.py -p COM15 build flash monitor`

The end device can join the network. The coordinator is Tasmota + Home Assistance ZigBee

## Scenario 2
1. `python3 esp_zb_mfg_tool.py -i 966b9f3ef98ae6059708 -m CAFEBEEF50C0FFED -c 0x07FFF800 -mn Espressif -mc 0x131B`
2. `idf.py -p COM15 erase-flash`
3. `esptool.py -p COM15 write_flash 0x116000 .\production_config_sector.bin`
4.  `idf.py -p COM15 build flash monitor`

The end device can't join the network.

This is my `partitions.csv` file:
```csv
# Name,   Type, SubType, Offset,  Size, Flags
# Note: if you have increased the bootloader size, make sure to update the offsets to avoid overlap
nvs,        data, nvs,      0x9000,  0x6000,
phy_init,   data, phy,      0xf000,  0x1000,
factory,    app,  factory,  0x10000, 1M,
zb_storage, data, fat,      0x111000, 16K,
zb_fct,     data, fat,      0x116000, 1K,
```
