### ISSUE TITLE
Error: ZB_ESP_MAC: MAC RX buffer is full! (TZ-202)

### ISSUE THREAD

**Issue by BogatovT** [espressif/esp-zigbee-sdk#53]
Hello!
When i receive many Zigbee packets from devices at the same time it leads to the RX buffer overflow. Sometimes it even leads to the core panic. 
How can i manage buffer sizes on the MAC layer?
ESP32-C6

**Comment by xieqinan** [comment]
Hi, 
The Rx buffer overflow issue should have been fixed in the latest  [esp-zigee-sdk](https://github.com/espressif/esp-zigbee-sdk/commit/335239a91faa0d9d69abea302375ca3ca9b1c214) version. Could you please update it and try again? 
If the problem still persists, please feel free to contact us with the log information that is helpful for us to fix problem.
